// providers/dyad.ts
import { ProviderConfig } from "../types"
import { DEFAULT_BASE_URLS, PROVIDER_IDS, PROVIDER_NAMES } from "../constants"

export const dyadConfig: ProviderConfig = {
	id: PROVIDER_IDS.DYAD,
	name: PROVIDER_NAMES[PROVIDER_IDS.DYAD],
	baseUrl: DEFAULT_BASE_URLS[PROVIDER_IDS.DYAD],
	models: [
		{
			id: "gpt-4o",
			name: "GPT-4 O - Dyad Tunnel",
			contextWindow: 128000,
			maxTokens: 4096,
			supportsImages: true,
			supportsPromptCache: true,
			inputPrice: 5.0,
			outputPrice: 15.0,
			cacheReadsPrice: 2.5,
			cacheWritesPrice: 5.0,
			isRecommended: true,
			provider: PROVIDER_IDS.DYAD,
		},
		{
			id: "gpt-4o-mini",
			name: "GPT-4 O Mini - Dyad Tunnel",
			contextWindow: 128000,
			maxTokens: 16384,
			supportsImages: true,
			supportsPromptCache: true,
			inputPrice: 0.15,
			outputPrice: 0.6,
			cacheReadsPrice: 0.075,
			cacheWritesPrice: 0.15,
			provider: PROVIDER_IDS.DYAD,
		},
		{
			id: "deepseek-chat",
			name: "DeepSeek Chat - Dyad Tunnel",
			contextWindow: 64000,
			maxTokens: 8192,
			supportsImages: false,
			supportsPromptCache: true,
			inputPrice: 0.14,
			outputPrice: 0.28,
			cacheReadsPrice: 0.014,
			cacheWritesPrice: 0.14,
			provider: PROVIDER_IDS.DYAD,
		},
		{
			id: "deepseek-reasoner",
			name: "DeepSeek R1 - Dyad Tunnel",
			contextWindow: 64000,
			maxTokens: 8192,
			supportsImages: false,
			supportsPromptCache: true,
			inputPrice: 0.55,
			outputPrice: 2.19,
			cacheReadsPrice: 0.14,
			cacheWritesPrice: 0.55,
			isThinkingModel: true,
			provider: PROVIDER_IDS.DYAD,
		},
	],
	requiredFields: ["apiKey"],
}
